services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Service aliases for better developer experience
    ai_dev_assistant.code_analyzer: '@Aria1991\AIDevAssistantBundle\Service\CodeAnalyzer'
    ai_dev_assistant.ai_manager: '@Aria1991\AIDevAssistantBundle\Service\AIManager'
    ai_dev_assistant.cache: '@Aria1991\AIDevAssistantBundle\Service\CacheService'

    Aria1991\AIDevAssistantBundle\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/AIDevAssistantBundle.php'

    # AI Providers with priority tags for ordered fallback
    Aria1991\AIDevAssistantBundle\Service\Provider\OpenAIProvider:
        arguments:
            $httpClient: '@http_client'
            $apiKey: '%env(default::OPENAI_API_KEY)%'
            $model: '%ai_dev_assistant.ai.providers.openai.model%'
            $maxTokens: '%ai_dev_assistant.ai.providers.openai.max_tokens%'
        tags:
            - { name: 'ai_dev_assistant.provider', priority: 100 }

    Aria1991\AIDevAssistantBundle\Service\Provider\AnthropicProvider:
        arguments:
            $httpClient: '@http_client'
            $apiKey: '%env(default::ANTHROPIC_API_KEY)%'
            $model: '%ai_dev_assistant.ai.providers.anthropic.model%'
            $maxTokens: '%ai_dev_assistant.ai.providers.anthropic.max_tokens%'
        tags:
            - { name: 'ai_dev_assistant.provider', priority: 80 }

    Aria1991\AIDevAssistantBundle\Service\Provider\GoogleProvider:
        arguments:
            $httpClient: '@http_client'
            $apiKey: '%env(default::GOOGLE_AI_API_KEY)%'
            $model: '%ai_dev_assistant.ai.providers.google.model%'
        tags:
            - { name: 'ai_dev_assistant.provider', priority: 60 }

    # AI Manager with compiler pass injection
    Aria1991\AIDevAssistantBundle\Service\AIManager:
        arguments:
            $providers: [] # Will be populated by AIProviderPass

    # Code Analyzers with service tags and priorities
    Aria1991\AIDevAssistantBundle\Service\Analyzer\SecurityAnalyzer:
        tags: 
            - { name: 'ai_dev_assistant.analyzer', priority: 100 }
    Aria1991\AIDevAssistantBundle\Service\Analyzer\QualityAnalyzer:
        tags: 
            - { name: 'ai_dev_assistant.analyzer', priority: 90 }
    Aria1991\AIDevAssistantBundle\Service\Analyzer\PerformanceAnalyzer:
        tags: 
            - { name: 'ai_dev_assistant.analyzer', priority: 80 }
    Aria1991\AIDevAssistantBundle\Service\Analyzer\DocumentationAnalyzer:
        tags: 
            - { name: 'ai_dev_assistant.analyzer', priority: 70 }

    # Main Code Analyzer Service with compiler pass injection
    Aria1991\AIDevAssistantBundle\Service\CodeAnalyzer:
        arguments:
            $analyzers: [] # Will be populated by AnalyzerPass
            $cacheService: '@Aria1991\AIDevAssistantBundle\Service\CacheService'

    # Cache Service
    Aria1991\AIDevAssistantBundle\Service\CacheService:
        arguments:
            $cache: '@cache.app'
            $ttl: '%ai_dev_assistant.cache.ttl%'
            $enabled: '%ai_dev_assistant.cache.enabled%'

    # Rate Limiter
    Aria1991\AIDevAssistantBundle\Service\RateLimiter:
        arguments:
            $cache: '@cache.app'

    # Commands
    Aria1991\AIDevAssistantBundle\Command\AnalyzeCodeCommand:
        tags:
            - { name: 'console.command' }

    Aria1991\AIDevAssistantBundle\Command\ConfigTestCommand:
        tags:
            - { name: 'console.command' }

    Aria1991\AIDevAssistantBundle\Command\InstallCommand:
        arguments:
            $projectDir: '%kernel.project_dir%'
        tags:
            - { name: 'console.command' }

    # Health Check Command (v1.2+)
    Aria1991\AIDevAssistantBundle\Command\HealthCheckCommand:
        tags:
            - { name: 'console.command' }

    # Advanced Cache Service (v1.3+)
    Aria1991\AIDevAssistantBundle\Service\AdvancedCacheService:
        arguments:
            $cache: '@cache.app'
            $logger: '@logger'
        tags:
            - { name: 'monolog.logger', channel: 'ai_dev_assistant' }

    # WebProfiler Data Collector (v1.4+) - only loaded when WebProfiler is available
    Aria1991\AIDevAssistantBundle\DataCollector\AIAnalysisDataCollector:
        arguments:
            $codeAnalyzer: '@Aria1991\AIDevAssistantBundle\Service\CodeAnalyzer'
            $aiManager: '@Aria1991\AIDevAssistantBundle\Service\AIManager'
        tags:
            - { name: 'data_collector', template: 'profiler/ai_analysis.html.twig', id: 'ai_analysis', priority: 300 }
